kind: pipeline
name: default

platform:
  os: darwin
  arch: amd64

steps:
  - name: integration
    image: node
    commands:
    - npm install
    - npm run build
    - npm run test
    - npm run lint 
