kind: pipeline
type: docker
name: LinuxAMD64

platform:
  os: linux
  arch: amd64

steps:
  - name: integration
    image: node:12
    commands:
    - npm ci
    - npm run build
    - npm run test
    - npm run lint 

---
kind: pipeline
type: docker
name: WindowsAMD64

platform:
  os: windows
  arch: amd64

steps:
  - name: integration
    image: node:12
    commands:
    - npm ci
    - npm run build
    - npm run test
    - npm run lint 
