kind: pipeline
type: docker
name: Node12LinuxAMD64

platform:
  os: linux
  arch: amd64

steps:
  - name: integration
    image: node:12
    commands:
    - npm ci
    - npm run build
    - npm run test
    - npm run lint 

---
kind: pipeline
type: docker
name: Node10LinuxAMD64

platform:
  os: linux
  arch: amd64

steps:
  - name: integration
    image: node:10
    commands:
    - npm ci
    - npm run build
    - npm run test
    - npm run lint 

---

kind: pipeline
type: docker
name: LinuxArm64

platform:
  os: linux
  arch: arm64

steps:
  - name: integration
    image: node:12
    commands:
    - npm ci
    - npm run build
    - npm run test
    - npm run lint 
